### ISSUE TITLE
ARTIFACT_URL does not support Github Artifacts

### ISSUE THREAD

**Issue by Chrico** [InstaWP/wordpress-testing-automation#18]
When using `actions/upload-artifact@v4`  and the returned `artifact-url` from output, it does not work due missing auth for the URL.

Is it possible to support "Github Artifacts" since there is already a `GITHUB_TOKEN` available and the `github.getOctokit(GITHUB_TOKEN)` uses it?

The workflow looks like following:

```yml
name: InstaWP WordPress Testing

on:
  push:
    branches:
      - insta-wp-built

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Create Plugin-ZIP
        run: yarn plugin-zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "my-plugin"
          path: ./my-plugin.zip

  create-wp-for-testing:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Start InstaWP
        uses: instawp/wordpress-testing-automation@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          # INSTAWP_TEMPLATE_SLUG: /* snip */
          # REPO_ID: /* snip */
          INSTAWP_ACTION: create-site-template
          ARTIFACT_URL: ${{ steps.build-artifact.artifact-url }}

```

----

## Links

- https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact
